discord/django/urls.py
from django.urls import path

from . import views

app_name = "bot-management"

urlpatterns = [
    path('', views.bot_landing, name='bot_landing'),
    path('log', views.bot_log, name='bot_log')
]

events/urls.py
from django.urls import path

from . import views

app_name = "events"

urlpatterns = [
    path('', views.index, name='event_index'),
    path('create/', views.create_event, name='create_event'),
    path('delete/<int:event_id>/', views.delete_event, name='delete_event')
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path('', views.index, name='users_index'),
    path('profile', views.profile, name='user_profile'),
    path('api/v1/confirm_discord', views.confirm_discord, name='confirm_discord')
]

whitehat/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView
from events.views import index as event_index
from discord.django.views import bot_landing

urlpatterns = [
    path('events/', include('events.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', event_index, name='home'),
    path('bot-management/', include('discord.django.urls')),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about')
]

events/models.py
from django.db import models
from django.utils import timezone

# Event Model

class Event(models.Model):

	DEFAULT_TITLE = "Ethical Hacking Meeting - Weekly Meetup"
	DEFAULT_LOCATION = "G01 at CSSE"
	DEFAULT_INFO = "Bring your laptops"

	title = models.CharField(max_length=100, default=DEFAULT_TITLE)
	location = models.CharField(max_length=100, default=DEFAULT_LOCATION)
	time = models.CharField(max_length=100)
	info = models.TextField(default=DEFAULT_INFO)
	date_created = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.time

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

htb_url_base = 'https://www.hackthebox.eu/badge/image/'
htb_profile_base = 'https://www.hackthebox.eu/profile/'

class Users(models.Model):

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, blank=True)
    discord_id = models.CharField(primary_key=True, max_length=255)
    full_name = models.CharField(max_length=255)
    link = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    htb = models.CharField(max_length=255, blank=True, null=True)
    discord_tag = models.CharField(max_length=255, blank=True, null=True)
    discord_avatar = models.CharField(max_length=255, blank=True, null=True)
    site_verified = models.BooleanField(default=False)
    site_key = models.CharField(max_length=32, blank=True, unique=True, default=uuid.uuid4().hex)

    def __str__(self):
        return self.discord_tag

    def get_htb_url(self):
        if self.htb:
            return htb_url_base + str(self.htb)
        else:
            return None

    def get_htb_profile(self):
        if self.htb:
            return htb_profile_base + str(self.htb)
        else:
            return None

events/forms.py
from django.forms import ModelForm
from django import forms

from .models import Event


class CreateEventForm(ModelForm):
    class Meta:
        model = Event
        fields = 'title', 'location', 'time', 'info'

    def __init__(self, *args, **kwargs):
        super(CreateEventForm, self).__init__(*args, **kwargs)
        for fname, f in self.fields.items():
            if fname == 'time':
                f.widget.attrs["class"] = "form-control"
                f.widget.attrs["id"] = "datetimepicker"
                f.widget.attrs["autocomplete"] = "off"
            f.widget.attrs["class"] = "form-control"

discord/django/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.contrib.admin.views.decorators import staff_member_required
from users.models import Users
from pathlib import Path

from django.http import HttpResponse

@staff_member_required()
def bot_landing(request):
    contents = Path('discord/logs/whitehat.log').read_text()
    c = {}
    return render(request, "discord/landing.html", c)

@staff_member_required()
def bot_log(request):
    contents = Path('discord/logs/whitehat.log').read_text()
    c = {'log': contents}
    return render(request, "discord/log.html", c)

events/views.py
from django.shortcuts import render, redirect, get_object_or_404
from dhooks import Webhook, Embed
from django.http import HttpResponse
from events.forms import CreateEventForm
from .utils import send_embed
from .models import Event
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib.admin.views.decorators import staff_member_required


def index(request):
    current_events = Event.objects.filter(time__gte=timezone.now()).order_by('time')
    previous_events = Event.objects.filter(time__lt=timezone.now()).order_by('time')
    c = {'current_events': current_events, 'previous_events': previous_events}
    return render(request, "index.html", c)


@staff_member_required
def create_event(request):
    form = CreateEventForm()
    if request.POST:
        print(request.POST)
        if request.user.is_staff:
            if CreateEventForm(request.POST).is_valid():
                CreateEventForm(request.POST).save()
                send_embed(request)
                messages.success(request, 'Event created and deployed to Discord!')
                return redirect("events:event_index")
            messages.error(request, 'Invalid Parameters for Event!')
    c = {'form': form }
    return render(request, "create_event.html", c)


@staff_member_required
def delete_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    event.delete()
    messages.success(request, 'Event successfully deleted!')
    return redirect("events:event_index")

users/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.contrib.admin.views.decorators import staff_member_required
from .models import Users

from django.http import HttpResponse

@staff_member_required()
def index(request):
    profiles = Users.objects.all()
    c = {'profiles': profiles }
    return render(request, "user_index.html", c)


@login_required
def profile(request):
    user_profile = get_object_or_404(Users, user=request.user)
    c = {'profile': user_profile}
    return render(request, "user_profile.html", c)


@login_required
def confirm_discord(request):
    user_profile = get_object_or_404(Users, user=request.user)
    success = False
    if user_profile.site_verified:
        success = True
    return JsonResponse({"success": success})

events/templates/create_event.html
{% extends "base.html" %}

{% block title %}
  Create Event
{% endblock %}

{% block page_header %}Create Event{% endblock %}

{% block body %}
  <div class="item-background">
    <form method="POST">
      {% csrf_token %}
      {% for field in form %}
        <div class="mb-2">{{ field.label }}</div>
        <div class="mb-2">{{ field }}</div>
      {% endfor %}
      {#    <input id="datetimepicker" type="text" name="test" autocomplete="off">#}
      <button type="button" class="btn btn-primary mt-3" data-toggle="modal" data-target="#exampleModal">
        Create Event
      </button>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
           aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Create Event</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Are you sure you want to create this event? Doing so will cause a server-wide notification on Discord.
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button class="btn btn-primary" type="submit">Create Event</button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>

  <script>
    $('#datetimepicker').datetimepicker({
      format: 'Y-m-d H:00'
    });
  </script>
{% endblock %}

events/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Events
{% endblock %}

{% block head %}
  <link href="{% static "css/tabs.css" %}" rel="stylesheet">
{% endblock %}

{% block page_header %}
  Events
  {% if user.is_staff %}
    <a href="{% url "events:create_event" %}" class="btn btn-primary float-right" style="color: #FFF">
      Create Event
    </a>
  {% endif %}
{% endblock %}

{% block body %}
  <div class="tab">
    <button class="tablinks" onclick="openCity(event, 'current')" id="default">Current Events</button>
    <button class="tablinks" onclick="openCity(event, 'previous')">Previous Events</button>
  </div>
  <div id="current" class="tabcontent mb-3">
    <div class="card-body">
      {% if not current_events %}
        <div class="alert alert-info mt-3">
          There are no upcoming events.
        </div>
      {% endif %}
      <div style="display: flex; flex-wrap: wrap; justify-content: space-between">
        {% for event in current_events %}
          <div class="card mb-2 bg-light" style="width: 100%">
            <div class="card-body">
              <div class="mb-2">
                <strong>{{ event.title }}</strong>
                {% if user.is_staff %}
                  <button type="button" class="btn btn-danger float-right" data-toggle="modal"
                          data-target="#modal_event_{{ event.id }}">
                    <i class="fa fa-trash"></i>
                  </button>

                  <!-- Modal -->
                  <div class="modal fade" id="modal_event_{{ event.id }}" tabindex="-1" role="dialog"
                       aria-labelledby="modal_event_{{ event.id }}Label"
                       aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="modal_event_{{ event.id }}Label">Delete Event</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          Are you sure you want to delete this event? Doing so will delete the event from the database,
                          however will not delete the event from the Discord channel.
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          <a href="{% url 'events:delete_event' event.id %}" class="float-right btn btn-danger"
                             style="color: #FFF">Delete Event</a>
                        </div>
                      </div>
                    </div>
                  </div>
                {% endif %}
              </div>
              <i class="fa fa-fw fa-map-marker-alt"></i> {{ event.location }}<br>
              <i class="fa fa-fw fa-calendar"></i> {{ event.time }}<br>
              <i class="fa fa-fw fa-info-circle"></i> {{ event.info }}
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>

  <div id="previous" class="tabcontent mb-3">
    <div class="card-body">
      {% if not previous_events %}
        <div class="alert alert-info mt-3">
          There are no previous events.
        </div>
      {% endif %}
      <div style="display: flex; flex-wrap: wrap; justify-content: space-between">
        {% for event in previous_events %}
          <div class="card mb-2 bg-light" style="width: 100%">
            <div class="card-body">
              <div class="mb-2">
                <strong>{{ event.title }}</strong>
                {% if user.is_staff %}
                  <button type="button" class="btn btn-danger float-right" data-toggle="modal"
                          data-target="#modal_event_{{ event.id }}">
                    <i class="fa fa-trash"></i>
                  </button>

                  <!-- Modal -->
                  <div class="modal fade" id="modal_event_{{ event.id }}" tabindex="-1" role="dialog"
                       aria-labelledby="modal_event_{{ event.id }}Label"
                       aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="modal_event_{{ event.id }}Label">Delete Event</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          Are you sure you want to delete this event? Doing so will delete the event from the database,
                          however will not delete the event from the Discord channel.
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          <a href="{% url 'events:delete_event' event.id %}" class="float-right btn btn-danger"
                             style="color: #FFF">Delete Event</a>
                        </div>
                      </div>
                    </div>
                  </div>
                {% endif %}
              </div>
              <i class="fa fa-fw fa-map-marker"></i> {{ event.location }}<br>
              <i class="fa fa-fw fa-calendar"></i> {{ event.time }}<br>
              <i class="fa fa-fw fa-info-circle"></i> {{ event.info }}
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>

  <script src="{% static "js/tabs.js" %}"></script>
{% endblock %}

users/templates/user_index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Registered Users
{% endblock %}

{% block page_header %}
  Registered Users
  <a href="{% url "bot-management:bot_landing" %}" class="btn btn-primary float-right" style="color: #FFF">
    Back
  </a>
{% endblock %}

{% block body %}
  <div class="alert alert-info">
    All currently registered <strong>Profiles</strong> using <strong>Whitehat's !register</strong> command. are
    displayed here.
  </div>
  <!-- Trigger Discord User Modal -->
  <button type="button" class="btn btn-primary mb-3" data-toggle="modal" data-target="#userModal">
    Show Online Users
  </button>

  <!-- Discord User Modal -->
  <div class="modal fade" id="userModal" tabindex="-1" role="dialog" aria-labelledby="userModalLabel"
       aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <iframe src="https://discordapp.com/widget?id=594900376508039169" height="600"
                allowtransparency="true" frameborder="0"></iframe>
      </div>
    </div>
  </div>
  <div class="item-background"
       style="display: flex; flex-wrap: wrap; justify-content: space-between; padding-bottom: 20px">
    {% for profile in profiles %}
      <a style="min-width: 49%; margin: 0 auto 10px auto" data-toggle="modal"
         data-target="#userModal_{{ profile.discord_id }}">
        <div class="card">
          <div class="card-body" style="text-align: center">
            <img src="{{ profile.discord_avatar }}" alt="discord_avatar_{{ profile.discord_id }}" height="50"
                 width="50" style="border-radius: 50%">
            <br>
            <div class="mt-1">
              {{ profile.discord_tag }}
            </div>
            <strong>{{ profile.full_name }}</strong>
            <br>

          </div>
        </div>
      </a>
      <div class="modal fade" id="userModal_{{ profile.discord_id }}" tabindex="-1" role="dialog"
           aria-labelledby="userModal_{{ profile.discord_id }}_Label"
           aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-body" style="text-align: center">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <img src="{{ profile.discord_avatar }}" alt="discord_avatar_{{ profile.discord_id }}" height="50"
                   width="50" style="border-radius: 50%"><br>
              <div class="mt-1">
                <strong>Full Name:</strong> {{ profile.full_name }}<br>
                <strong>Discord Tag:</strong> {{ profile.discord_tag }}<br>
                <strong>Description:</strong> {{ profile.description }}<br>
                {% if profile.link %}
                  <strong>Link:</strong> <a href="{{ profile.link }}">{{ profile.link }}</a><br>
                {% endif %}
                {% if profile.htb %}
                  <a href="{{ profile.get_htb_profile }}"><img class="mt-2" src="{{ profile.get_htb_url }}" alt="htb_{{ profile.discord_id }}"></a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>

    {% endfor %}
  </div>
{% endblock %}

users/templates/user_profile.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  User Profile
{% endblock %}

{% block page_header %}
  User Profile
{% endblock %}

{% block body %}
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#discordModal">
    Link Discord Account
  </button>

  <!-- Modal -->
  <div class="modal fade" id="discordModal" tabindex="-1" role="dialog" aria-labelledby="discordModalLongTitle"
       aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content" id="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="discordModalLongTitle">Link Discord Account</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="alert alert-info">
            To link your accounts please copy the key below and direct message it to the <strong>White Hat</strong> bot
            (White Hat#4699) using the <strong>!key</strong> command, then <strong>Confirm Link</strong>.
          </div>
          <div style="text-align: center">
            <code id="siteKey">!key {{ profile.site_key }}</code>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Copy to Clipboard"
             style="color: #FFF; cursor: pointer" id="copySiteKey"><i class="fa fa-fw fa-copy"></i></button>
          <a class="btn btn-primary" style="color: #FFF; cursor: pointer" onclick="return confirmDiscord()">Confirm
            Link</a>
        </div>
      </div>
    </div>
  </div>
  <script>
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    function getCookie(name) {
      let cookieValue = null;
      if (document.cookie && document.cookie !== '') {
        let cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
          let cookie = cookies[i].trim();
          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1) === (name + '=')) {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }

    let csrftoken = getCookie('csrftoken');

    $.ajaxSetup({
      beforeSend: function (xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });

    function confirmDiscord() {
      $.ajax({
        type: "POST",
        url: "{% url 'users:confirm_discord' %}",
        dataType: "json",
        data: {},
        success: function (resp) {
          if (resp.success) {
            alert("Your Discord Profile was successfully linked to the website.");
            window.location.reload(false);
          } else {
            alert("The link was unsuccessful. Please confirm you have sent the key using the correct parameters.")
          }
        }
      });
    }

    document.getElementById("copySiteKey").addEventListener("click", function() {
      let modalContent = document.getElementById('modal-content');
      let textarea = document.createElement("input");
      textarea.value = document.getElementById("siteKey").innerText;
      modalContent.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      modalContent.removeChild(textarea);
    });
  </script>
{% endblock %}